### ISSUE TITLE
NPE on new server build

### ISSUE THREAD

**Issue by kreezxil** [Mrbysco/ageing-mobs#2]
## Server Info
* Minecraft Version: 1.15.2
* Forge Version: 31.2.37
* Mod Version: 1.0.0
* Java Version: 8

## Issue Description
when a mob ages it crashes, is what i think its doing. not sure why i have to witness that.

## Reproduce Steps
either this mod is a great success or it doesn't work on forge build 31.2.37. I don't intend to roll down to the other versions. if you create a patch let me know as i'm removing it for now.

## Additional Information

crash report: 
http://paste.ubuntu.com/p/RX6mcxmQgQ/

fml server latest: 
http://paste.ubuntu.com/p/7R8ZhYXbYZ/

**Comment by Mrbysco** [comment]
Could you try out this version and see if it fixes your issue? https://github.com/Mrbysco/ageing-mobs/releases/tag/1.1.0

**Comment by kreezxil** [comment]
just got back from hospital. will give it a whirl tomorrow, will let ya
know what it does.

**Comment by kreezxil** [comment]
ok i have it installed, i will now spawn some mobs in a cage and see what happens

**Comment by kreezxil** [comment]
you've fixed it, you can push this to curseforge. i've got zombies ageing without crashing the server now.

**Comment by Mrbysco** [comment]
Thank you for testing. Will also release a 1.16 fix of the bug.
Also stay safe

**Comment by kreezxil** [comment]
Too late, i punctured my plantar fascia on my right foot. It was inevitable
apparently. I had a huge bone spur on the front of the heel. Now i've got
lots of therapy to do and ginger tea to drink.
