### ISSUE TITLE
[1.15.2] extreme server tick usage crash

### ISSUE THREAD

**Issue by kreezxil** [Mrbysco/ageing-mobs#3]
## Client Info
* Minecraft Version: 1.15.2

* Forge Version: 31.2.41
* Mod Version: 1.1.0
* Java Version: 8

## Issue Description
ageing mods taking an excessive amount of time to tick

## Reproduce Steps
letting the mod run

- **crash report 1**: https://gist.github.com/e23520cd0092b95b0c08e9de31683c66
- **crash report 2** https://gist.github.com/6bfa94527ad41f0797ca46dbcef09275

**Comment by Mrbysco** [comment]
Looking into it.

**Comment by Mrbysco** [comment]
Could you test out this test-release? https://github.com/Mrbysco/ageing-mobs/releases/tag/1.2.0
I've done some improvement on the code
